version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "--protected-mode", "no", "--bind", "0.0.0.0"]
    networks:
      - goredis-net

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=k6db
      - INFLUXDB_HTTP_MAX_BODY_SIZE=0
    networks:
      - goredis-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - goredis-net

  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./scripts:/scripts
    network_mode: host
    environment:
      - K6_OUT=influxdb=http://localhost:8086/k6db
      - K6_INFLUXDB_PUSH_INTERVAL=10s
      - K6_INFLUXDB_PUSH_TIMEOUT=30s

  postgres:
    image: postgres:latest
    container_name: goredis-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5888:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - goredis-net

networks:
  goredis-net:
    driver: bridge

volumes:
  pgdata:
